#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

PROG=/usr/bin/orasrs-lite
CONF=/etc/config/orasrs

start_service() {
	config_load orasrs
	
	local enabled
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 0 ] && return 0
	
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_set_param file $CONF
	procd_set_param stdout 1
	procd_set_param stderr 1
	
	# Resource limits for embedded devices
	procd_set_param limits core="0"
	procd_set_param limits nofile="1024 1024"
	
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "orasrs"
}

reload_service() {
	stop
	start
}
