// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILayerZeroEndpoint$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILayerZeroEndpoint";
  readonly sourceName: "isolated_contracts/CrossChainInterfaces.sol";
  readonly abi: [{"inputs":[{"internalType":"uint16","name":"_dstChainId","type":"uint16"},{"internalType":"address","name":"_userApplication","type":"address"},{"internalType":"bytes","name":"_payload","type":"bytes"},{"internalType":"bool","name":"_payInZRO","type":"bool"},{"internalType":"bytes","name":"_adapterParam","type":"bytes"}],"name":"estimateFees","outputs":[{"internalType":"uint256","name":"nativeFee","type":"uint256"},{"internalType":"uint256","name":"zroFee","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint16","name":"_dstChainId","type":"uint16"},{"internalType":"bytes","name":"_destination","type":"bytes"},{"internalType":"bytes","name":"_payload","type":"bytes"},{"internalType":"address payable","name":"_refundAddress","type":"address"},{"internalType":"address","name":"_zroPaymentAddress","type":"address"},{"internalType":"bytes","name":"_adapterParams","type":"bytes"}],"name":"send","outputs":[],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/isolated_contracts/CrossChainInterfaces.sol";
  readonly buildInfoId: "solc-0_8_19-22d079e1c32bc46a1bc5b10cbc249f0401cf74f3";
};

export interface LzApp$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LzApp";
  readonly sourceName: "isolated_contracts/CrossChainInterfaces.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"required","type":"uint256"},{"internalType":"uint256","name":"provided","type":"uint256"}],"name":"LzAppInsufficientFee","type":"error"},{"inputs":[{"internalType":"address","name":"endpoint","type":"address"}],"name":"LzAppInvalidEndpoint","type":"error"},{"inputs":[{"internalType":"uint16","name":"srcChainId","type":"uint16"},{"internalType":"bytes","name":"trustedRemote","type":"bytes"},{"internalType":"bytes","name":"source","type":"bytes"}],"name":"LzAppInvalidPath","type":"error"},{"inputs":[],"name":"LzAppNoAdapterParams","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint16","name":"_srcChainId","type":"uint16"},{"indexed":true,"internalType":"bytes","name":"_srcAddress","type":"bytes"}],"name":"UaForceResumeReceive","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint16","name":"_dstChainId","type":"uint16"},{"indexed":true,"internalType":"bytes","name":"_dstAddress","type":"bytes"}],"name":"UaForceResumeSend","type":"event"},{"inputs":[],"name":"lzEndpoint","outputs":[{"internalType":"contract ILayerZeroEndpoint","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint16","name":"","type":"uint16"}],"name":"trustedRemoteLookup","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/isolated_contracts/CrossChainInterfaces.sol";
  readonly buildInfoId: "solc-0_8_19-22d079e1c32bc46a1bc5b10cbc249f0401cf74f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILayerZeroEndpoint"]: ILayerZeroEndpoint$Type
    ["LzApp"]: LzApp$Type;
    ["isolated_contracts/CrossChainInterfaces.sol:ILayerZeroEndpoint"]: ILayerZeroEndpoint$Type
    ["isolated_contracts/CrossChainInterfaces.sol:LzApp"]: LzApp$Type;
  }
}